//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 25, 25")]
        public global::System.Drawing.Color Grid_Colour {
            get {
                return ((global::System.Drawing.Color)(this["Grid_Colour"]));
            }
            set {
                this["Grid_Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Bottom_Of_Play_Area {
            get {
                return ((int)(this["Bottom_Of_Play_Area"]));
            }
            set {
                this["Bottom_Of_Play_Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Right_Of_Play_Area {
            get {
                return ((int)(this["Right_Of_Play_Area"]));
            }
            set {
                this["Right_Of_Play_Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Left_Of_Play_Area {
            get {
                return ((int)(this["Left_Of_Play_Area"]));
            }
            set {
                this["Left_Of_Play_Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int Top_Of_Play_Area {
            get {
                return ((int)(this["Top_Of_Play_Area"]));
            }
            set {
                this["Top_Of_Play_Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Number_Of_Columns {
            get {
                return ((int)(this["Number_Of_Columns"]));
            }
            set {
                this["Number_Of_Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Number_Of_Rows {
            get {
                return ((int)(this["Number_Of_Rows"]));
            }
            set {
                this["Number_Of_Rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int Cell_Width {
            get {
                return ((int)(this["Cell_Width"]));
            }
            set {
                this["Cell_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int Cell_Height {
            get {
                return ((int)(this["Cell_Height"]));
            }
            set {
                this["Cell_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Left_Grid_Margin {
            get {
                return ((int)(this["Left_Grid_Margin"]));
            }
            set {
                this["Left_Grid_Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int Top_Grid_Margin {
            get {
                return ((int)(this["Top_Grid_Margin"]));
            }
            set {
                this["Top_Grid_Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Line_Clear_Color {
            get {
                return ((global::System.Drawing.Color)(this["Line_Clear_Color"]));
            }
            set {
                this["Line_Clear_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Game_Starting_Timer_Interval {
            get {
                return ((int)(this["Game_Starting_Timer_Interval"]));
            }
            set {
                this["Game_Starting_Timer_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Number_Of_Lines_Needed_To_Level_Up {
            get {
                return ((int)(this["Number_Of_Lines_Needed_To_Level_Up"]));
            }
            set {
                this["Number_Of_Lines_Needed_To_Level_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public int Level_Up_Timer_Decrease {
            get {
                return ((int)(this["Level_Up_Timer_Decrease"]));
            }
            set {
                this["Level_Up_Timer_Decrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Winning_Level {
            get {
                return ((int)(this["Winning_Level"]));
            }
            set {
                this["Winning_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("highScores.xml")]
        public string HighScores_FilePath {
            get {
                return ((string)(this["HighScores_FilePath"]));
            }
            set {
                this["HighScores_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You made a new High Score!!!!!!!")]
        public string Losing_Game_Text {
            get {
                return ((string)(this["Losing_Game_Text"]));
            }
            set {
                this["Losing_Game_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You didn\'t make the High Scores")]
        public string Winning_Game_Text {
            get {
                return ((string)(this["Winning_Game_Text"]));
            }
            set {
                this["Winning_Game_Text"] = value;
            }
        }
    }
}
